//
// Created by ksohe on 5/23/2024.
//

#include "static_gstreamer.h"

#include <gst/gst.h>
#include <gio/gio.h>

/* Call this function to load GIO modules */
static void
gst_android_load_gio_modules (void)
{
    GTlsBackend *backend;
    const gchar *ca_certs;

    GST_G_IO_MODULE_LOAD(openssl);

    ca_certs = g_getenv ("CA_CERTIFICATES");

    backend = g_tls_backend_get_default ();
    if (backend && ca_certs) {
        GTlsDatabase *db;
        GError *error = NULL;

        db = g_tls_file_database_new (ca_certs, &error);
        if (db) {
            g_tls_backend_set_default_database (backend, db);
            g_object_unref (db);
        } else {
            g_warning ("Failed to create a database from file: %s",
                       error ? error->message : "Unknown");
        }
    }
}
/* This is called by gst_init() */
void
gst_init_static_plugins (void)
{
    GST_PLUGIN_STATIC_REGISTER(coreelements);  GST_PLUGIN_STATIC_REGISTER(coretracers);  GST_PLUGIN_STATIC_REGISTER(adder);  GST_PLUGIN_STATIC_REGISTER(app);  GST_PLUGIN_STATIC_REGISTER(audioconvert);  GST_PLUGIN_STATIC_REGISTER(audiomixer);  GST_PLUGIN_STATIC_REGISTER(audiorate);  GST_PLUGIN_STATIC_REGISTER(audioresample);  GST_PLUGIN_STATIC_REGISTER(audiotestsrc);  GST_PLUGIN_STATIC_REGISTER(compositor);  GST_PLUGIN_STATIC_REGISTER(gio);  GST_PLUGIN_STATIC_REGISTER(overlaycomposition);  GST_PLUGIN_STATIC_REGISTER(pango);  GST_PLUGIN_STATIC_REGISTER(rawparse);  GST_PLUGIN_STATIC_REGISTER(typefindfunctions);  GST_PLUGIN_STATIC_REGISTER(videoconvertscale);  GST_PLUGIN_STATIC_REGISTER(videorate);  GST_PLUGIN_STATIC_REGISTER(videotestsrc);  GST_PLUGIN_STATIC_REGISTER(volume);  GST_PLUGIN_STATIC_REGISTER(autodetect);  GST_PLUGIN_STATIC_REGISTER(videofilter);  GST_PLUGIN_STATIC_REGISTER(insertbin);  GST_PLUGIN_STATIC_REGISTER(switchbin);  GST_PLUGIN_STATIC_REGISTER(fallbackswitch);  GST_PLUGIN_STATIC_REGISTER(livesync);  GST_PLUGIN_STATIC_REGISTER(rsinter);  GST_PLUGIN_STATIC_REGISTER(rstracers);  GST_PLUGIN_STATIC_REGISTER(threadshare);  GST_PLUGIN_STATIC_REGISTER(togglerecord);  GST_PLUGIN_STATIC_REGISTER(playback);  GST_PLUGIN_STATIC_REGISTER(uriplaylistbin);  GST_PLUGIN_STATIC_REGISTER(subparse);  GST_PLUGIN_STATIC_REGISTER(ogg);  GST_PLUGIN_STATIC_REGISTER(theora);  GST_PLUGIN_STATIC_REGISTER(vorbis);  GST_PLUGIN_STATIC_REGISTER(opus);  GST_PLUGIN_STATIC_REGISTER(adaptivedemux2);  GST_PLUGIN_STATIC_REGISTER(alaw);  GST_PLUGIN_STATIC_REGISTER(amrnb);  GST_PLUGIN_STATIC_REGISTER(amrwbdec);  GST_PLUGIN_STATIC_REGISTER(apetag);  GST_PLUGIN_STATIC_REGISTER(audioparsers);  GST_PLUGIN_STATIC_REGISTER(auparse);  GST_PLUGIN_STATIC_REGISTER(avi);  GST_PLUGIN_STATIC_REGISTER(dv);  GST_PLUGIN_STATIC_REGISTER(flac);  GST_PLUGIN_STATIC_REGISTER(flv);  GST_PLUGIN_STATIC_REGISTER(flxdec);  GST_PLUGIN_STATIC_REGISTER(icydemux);  GST_PLUGIN_STATIC_REGISTER(id3demux);  GST_PLUGIN_STATIC_REGISTER(isomp4);  GST_PLUGIN_STATIC_REGISTER(jpeg);  GST_PLUGIN_STATIC_REGISTER(lame);  GST_PLUGIN_STATIC_REGISTER(matroska);  GST_PLUGIN_STATIC_REGISTER(mpg123);  GST_PLUGIN_STATIC_REGISTER(mulaw);  GST_PLUGIN_STATIC_REGISTER(multipart);  GST_PLUGIN_STATIC_REGISTER(png);  GST_PLUGIN_STATIC_REGISTER(speex);  GST_PLUGIN_STATIC_REGISTER(taglib);  GST_PLUGIN_STATIC_REGISTER(vpx);  GST_PLUGIN_STATIC_REGISTER(wavenc);  GST_PLUGIN_STATIC_REGISTER(wavpack);  GST_PLUGIN_STATIC_REGISTER(wavparse);  GST_PLUGIN_STATIC_REGISTER(xingmux);  GST_PLUGIN_STATIC_REGISTER(y4menc);  GST_PLUGIN_STATIC_REGISTER(adpcmdec);  GST_PLUGIN_STATIC_REGISTER(adpcmenc);  GST_PLUGIN_STATIC_REGISTER(assrender);  GST_PLUGIN_STATIC_REGISTER(bz2);  GST_PLUGIN_STATIC_REGISTER(codecalpha);  GST_PLUGIN_STATIC_REGISTER(codectimestamper);  GST_PLUGIN_STATIC_REGISTER(dash);  GST_PLUGIN_STATIC_REGISTER(dvbsubenc);  GST_PLUGIN_STATIC_REGISTER(dvbsuboverlay);  GST_PLUGIN_STATIC_REGISTER(dvdspu);  GST_PLUGIN_STATIC_REGISTER(hls);  GST_PLUGIN_STATIC_REGISTER(id3tag);  GST_PLUGIN_STATIC_REGISTER(ivfparse);  GST_PLUGIN_STATIC_REGISTER(midi);  GST_PLUGIN_STATIC_REGISTER(mxf);  GST_PLUGIN_STATIC_REGISTER(openh264);  GST_PLUGIN_STATIC_REGISTER(opusparse);  GST_PLUGIN_STATIC_REGISTER(pcapparse);  GST_PLUGIN_STATIC_REGISTER(pnm);  GST_PLUGIN_STATIC_REGISTER(rfbsrc);  GST_PLUGIN_STATIC_REGISTER(siren);  GST_PLUGIN_STATIC_REGISTER(smoothstreaming);  GST_PLUGIN_STATIC_REGISTER(subenc);  GST_PLUGIN_STATIC_REGISTER(videoparsersbad);  GST_PLUGIN_STATIC_REGISTER(y4mdec);  GST_PLUGIN_STATIC_REGISTER(jpegformat);  GST_PLUGIN_STATIC_REGISTER(gdp);  GST_PLUGIN_STATIC_REGISTER(rsvg);  GST_PLUGIN_STATIC_REGISTER(openjpeg);  GST_PLUGIN_STATIC_REGISTER(spandsp);  GST_PLUGIN_STATIC_REGISTER(sbc);  GST_PLUGIN_STATIC_REGISTER(zbar);  GST_PLUGIN_STATIC_REGISTER(androidmedia);  GST_PLUGIN_STATIC_REGISTER(cdg);  GST_PLUGIN_STATIC_REGISTER(claxon);  GST_PLUGIN_STATIC_REGISTER(dav1d);  GST_PLUGIN_STATIC_REGISTER(rsclosedcaption);  GST_PLUGIN_STATIC_REGISTER(ffv1);  GST_PLUGIN_STATIC_REGISTER(fmp4);  GST_PLUGIN_STATIC_REGISTER(mp4);  GST_PLUGIN_STATIC_REGISTER(gif);  GST_PLUGIN_STATIC_REGISTER(hsv);  GST_PLUGIN_STATIC_REGISTER(lewton);  GST_PLUGIN_STATIC_REGISTER(rav1e);  GST_PLUGIN_STATIC_REGISTER(json);  GST_PLUGIN_STATIC_REGISTER(rspng);  GST_PLUGIN_STATIC_REGISTER(regex);  GST_PLUGIN_STATIC_REGISTER(textwrap);  GST_PLUGIN_STATIC_REGISTER(textahead);  GST_PLUGIN_STATIC_REGISTER(tcp);  GST_PLUGIN_STATIC_REGISTER(rtsp);  GST_PLUGIN_STATIC_REGISTER(rtp);  GST_PLUGIN_STATIC_REGISTER(rtpmanager);  GST_PLUGIN_STATIC_REGISTER(soup);  GST_PLUGIN_STATIC_REGISTER(udp);  GST_PLUGIN_STATIC_REGISTER(dtls);  GST_PLUGIN_STATIC_REGISTER(netsim);  GST_PLUGIN_STATIC_REGISTER(rist);  GST_PLUGIN_STATIC_REGISTER(rtmp2);  GST_PLUGIN_STATIC_REGISTER(rtpmanagerbad);  GST_PLUGIN_STATIC_REGISTER(rtponvif);  GST_PLUGIN_STATIC_REGISTER(sctp);  GST_PLUGIN_STATIC_REGISTER(sdpelem);  GST_PLUGIN_STATIC_REGISTER(srtp);  GST_PLUGIN_STATIC_REGISTER(srt);  GST_PLUGIN_STATIC_REGISTER(webrtc);  GST_PLUGIN_STATIC_REGISTER(nice);  GST_PLUGIN_STATIC_REGISTER(rtspclientsink);  GST_PLUGIN_STATIC_REGISTER(aws);  GST_PLUGIN_STATIC_REGISTER(hlssink3);  GST_PLUGIN_STATIC_REGISTER(ndi);  GST_PLUGIN_STATIC_REGISTER(rsonvif);  GST_PLUGIN_STATIC_REGISTER(raptorq);  GST_PLUGIN_STATIC_REGISTER(reqwest);  GST_PLUGIN_STATIC_REGISTER(rsrtp);  GST_PLUGIN_STATIC_REGISTER(rsrtsp);  GST_PLUGIN_STATIC_REGISTER(webrtchttp);  GST_PLUGIN_STATIC_REGISTER(rswebrtc);  GST_PLUGIN_STATIC_REGISTER(opengl);  GST_PLUGIN_STATIC_REGISTER(ipcpipeline);  GST_PLUGIN_STATIC_REGISTER(opensles);
    gst_android_load_gio_modules ();
}
